#app
server:
  port: 29001
  servlet:
    context-path: /ad-check
#spring
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true

  # DATABASE CONFIG
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.1.100.73:3306/ad_check?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: home
      password: home_123
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin
      initialSize: 5                                 #初始化连接大小
      minIdle: 5                                     #最小连接池数量
      maxActive: 20                                  #最大连接池数量
      maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL            #测试连接
      testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
      filters: stat,wall                             #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filter:
        wall:
          enabled: true
          config:
            multiStatementAllow: true                #允许多条sql一起执行,是为了自己上传originData的时候能批量执行insert sql
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录

mybatis-plus:
  mapper-locations: classpath:mapping/**/*.xml
  typeAliasesPackage: ad.home.pojo.**
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断" 这个属性很重要，如果每次都是更新然后修改的话，可以直接使用IGNORED
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    #      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    ad:
      home:
        dao: debug
  config: classpath:logback.xml
